### ISSUE TITLE
Промежуточное задание 12 спринта

### ISSUE THREAD

**Issue by PetrutikSA** [PetrutikSA/java-filmorate#7]
Все изменения проведены в ветке **sql-scheme**.
В модель фильма было добавлены:  
    _private Genre genre;_ 
    _private Set<Rating> rating;_
Соответствующе перечисления были добавлены в папку enums - _Genre, Rating_.

В модель пользователя был откорректирован список друзей - Map, в котором значение - статус подтвержденный друг или нет.  
    _private Map<Integer, FriendshipStatus> friendsId;_
Соответствующее перечисление было добавлено в папку enums - _FriendshipStatus_.

Схема проекта БД, описание и примеры запросов размещен в файле README.md.
Смеха БД:

![DBDiagram](https://github.com/PetrutikSA/java-filmorate/assets/158184128/a79482df-c8cd-440c-a008-0e9d142c9756)

**Comment by Nadezhdushka92** [comment]
Отлично, Станислав, ты хорошо потрудился!

**Comment by Nadezhdushka92** [comment]
В описании опечатка таблиц небольшая опечатка в названии таблицы пользователей (наверное копи паст):
films
Содержит основную информацию о пользователе.

**Comment by Nadezhdushka92** [comment]
В остальном всё замечательно! Желаю удачи в следующих спринтах :)

**Comment by PetrutikSA** [comment]
Спасибо, да, действительно закопипастил немного лишнего)
Тебе тоже удачи в следующих спринтах!)
